
--SELECT * FROM sys.schemas;

/* Schema Creation */
CREATE SCHEMA MESSAGES_SCHEMA;
GO

/* Tables Creation */

-- Table: MESSAGES
CREATE TABLE MESSAGES_SCHEMA.MESSAGES (
    ID int  IDENTITY(1,1) PRIMARY KEY,
    CONTENT nvarchar(100)  NOT NULL,
    TYPE_ID int  NOT NULL,
    DATE datetime  NOT NULL
);

-- Table: MESSAGE_COLORS
CREATE TABLE MESSAGES_SCHEMA.MESSAGE_COLORS (
    ID int  NOT NULL,
    COLOR nvarchar(30)  NOT NULL,
    CONSTRAINT MESSAGE_COLORS_pk PRIMARY KEY  (ID)
);

-- Table: MESSAGE_TYPES
CREATE TABLE MESSAGES_SCHEMA.MESSAGE_TYPES (
    ID int  NOT NULL,
    TYPE nvarchar(30)  NOT NULL,
    COLOR_ID int  NOT NULL,
    CONSTRAINT MESSAGE_TYPES_pk PRIMARY KEY  (ID)
);

/* foreign keys */

-- Reference: MESSAGES_MESSAGE_TYPES (table: MESSAGES)
ALTER TABLE [MESSAGES_SCHEMA].[MESSAGES] ADD CONSTRAINT MESSAGES_MESSAGE_TYPES
    FOREIGN KEY (TYPE_ID)
    REFERENCES [MESSAGES_SCHEMA].[MESSAGE_TYPES](ID);

-- Reference: MESSAGE_TYPES_COLOR (table: MESSAGE_TYPES)
ALTER TABLE [MESSAGES_SCHEMA].[MESSAGE_TYPES] ADD CONSTRAINT MESSAGE_TYPES_COLOR
    FOREIGN KEY (COLOR_ID)
    REFERENCES [MESSAGES_SCHEMA].[MESSAGE_COLORS](ID);
