//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModularisTest.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSAGES
    {
        public int ID { get; set; }
        public string CONTENT { get; set; }
        public int TYPE_ID { get; set; }
        public System.DateTime DATE { get; set; }
    
        public virtual MESSAGE_TYPES MESSAGE_TYPES { get; set; }
    }
}
