//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModularisTest.Models.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LocalEntities : DbContext
    {
        public LocalEntities()
            : base("name=LocalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MESSAGE_COLORS> MESSAGE_COLORS { get; set; }
        public virtual DbSet<MESSAGE_TYPES> MESSAGE_TYPES { get; set; }
        public virtual DbSet<MESSAGES> MESSAGES { get; set; }
    }
}
